module.exports =  `
  type User {
    name: String!
    posts: [Post]
    comments: [Comment]
  }

  type Comment {
    user: User!
    desc: String!
  }

  type Post {
    title: String!
    user: User!
    comments: [Comment]
  }

  type Query {
    allPosts: [Post]
  }
`;