module.exports =  `
  type User {
    id: Int!
    name: String!
    secret: String!
  }

  type Comment {
    author: User!
    desc: String!
  }

  type Post {
    title: String!
    author: User!
    comments: [Comment]
  }

  type Query {
    allPosts: [Post]
  }
`;